# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-22 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_siteconfiguration_badges_letters'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'یادگاری به دیگران', 'verbose_name_plural': 'یادگاری به دیگران'},
        ),
        migrations.AlterModelOptions(
            name='commentreviewaccess',
            options={'verbose_name': 'دسترسی بازنگری یادگاری\u200cها', 'verbose_name_plural': 'دسترسی بازنگری یادگاری\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='opinion',
            options={'verbose_name': 'یادگاری به دوره', 'verbose_name_plural': 'یادگاری به دوره'},
        ),
        migrations.AlterModelOptions(
            name='placeholder',
            options={'verbose_name': 'متن پس\u200cزمینه', 'verbose_name_plural': 'متن\u200cهای پس\u200cزمینه'},
        ),
        migrations.AlterModelOptions(
            name='siteconfiguration',
            options={'verbose_name': 'تنظیمات مدیریتی سایت'},
        ),
        migrations.AlterModelOptions(
            name='themost',
            options={'verbose_name': 'آیتمِ ترین', 'verbose_name_plural': 'آیتم\u200cهای ترین'},
        ),
        migrations.AlterModelOptions(
            name='themostcategory',
            options={'verbose_name': 'دسته\u200cبندی\u200cهای ترین', 'verbose_name_plural': 'دسته\u200cبندی\u200cهای ترین'},
        ),
        migrations.AlterModelOptions(
            name='timeline',
            options={'verbose_name': 'آیتم\u200cهای گاه\u200cشمار', 'verbose_name_plural': 'آیتم\u200cهای گاه\u200cشمار'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربران', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'پروفایل\u200cهای کاربران', 'verbose_name_plural': 'پروفایل\u200cهای کاربران'},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'verbose_name': 'رای\u200c به ترین\u200cها', 'verbose_name_plural': 'رای\u200cها به ترین\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='wordvote',
            options={'verbose_name': 'کلمات شترگاوپلنگ', 'verbose_name_plural': 'کلمات شترگاوپلنگ'},
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='single_suggestion',
            field=models.BooleanField(default=False, help_text='در صورت انتخاب این گزینه، کلمات پیشنهادی در شترگاوپلنگ فقط از کلمات ارسال شده برای خود آن شخص خواهد بود. در غیر این صورت، همه کلمات ارسالی برای همه افراد برای این فرد پیشنهاد داده می\u200cشود.', verbose_name='شخصی\u200cسازی کلمات شترگاوپلنگ'),
        ),
    ]
