# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-27 14:33
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.fields
import main.models
import main.storage


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190622_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commenter', to='main.UserProfile', verbose_name='فرستنده متن'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_anonymous',
            field=models.BooleanField(default=False, verbose_name='گمنام است؟'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='review_state',
            field=main.fields.EnumField(default='submitted', enum=main.models.CommentState, max_length=13, verbose_name='وضعیت بررسی'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='main.UserProfile', verbose_name='گیرنده متن'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='متن یادگاری'),
        ),
        migrations.AlterField(
            model_name='commentreviewaccess',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, help_text='در این قسمت می\u200cتوانید نام کاربری دانشجویانی که این شخض قصد دارد متن\u200cهای آنها را مورد بازنگری قرار دهد مشخص می\u200cکنید.<br>جهبه سمت راست نشان\u200cدهنده افرادی هست که انتخاب شده\u200cاند.<br>', related_name='_commentreviewaccess_assigned_users_+', to='main.UserProfile', verbose_name='نام کاربری افرادی که قصد دارد متن آنها را بازنگری کند.'),
        ),
        migrations.AlterField(
            model_name='commentreviewaccess',
            name='user',
            field=models.OneToOneField(help_text='نام کاربری شخصی که قرار است بازنگری را انجام دهد.', on_delete=django.db.models.deletion.CASCADE, related_name='review_access', to=settings.AUTH_USER_MODEL, verbose_name='نام کاربری ناظر مورد نظر'),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='subject',
            field=models.CharField(max_length=160, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='teller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opinions', to='main.UserProfile', verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='text',
            field=models.TextField(verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='placeholder',
            name='text',
            field=models.TextField(verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='badges_letters',
            field=models.CharField(default='ce94', help_text='نشان چیست؟ نشان همون دایره\u200cهای کوچیکی هست که زیر اسم افراد توی صفحه ثبتنام وجود داره.<br>می\u200cتونید انتخاب کنید که اون\u200cها چه حروف یا اعدادی باشند. چهار حرف انگلیسی یا عدد انتخاب کنید.', max_length=4, verbose_name='حروفِ نشان\u200cها'),
        ),
        migrations.AlterField(
            model_name='themost',
            name='category',
            field=models.ForeignKey(blank=True, help_text='این فیلد نشان\u200cدهنده دسته\u200cای هست که این ترین در آن قرار می\u200cگیرد. <br>دسته ----- نشان\u200cدهنده دسته پیشفرض هست که کاربران هنگام ثبتنام اجازه شرکت در آن را دادند/ندادند.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mosts', to='main.TheMostCategory', verbose_name='دسته این آیتم'),
        ),
        migrations.AlterField(
            model_name='themost',
            name='is_released',
            field=models.BooleanField(default=False, help_text='با انتشار این آیتم، کاربران اجازه رای دادن به آن را پیدا می\u200cکنند.(به شرطی که اجازه شرکت در این دسته را داده باشند)', verbose_name='انتشار این آیتم'),
        ),
        migrations.AlterField(
            model_name='themost',
            name='text',
            field=models.TextField(verbose_name='عنوانِ ترین'),
        ),
        migrations.AlterField(
            model_name='themostcategory',
            name='can_register',
            field=models.BooleanField(default=True, help_text='با زدن این تیک، دانشجویان می\u200cتوانند اجازه شرکت در این دسته را بدهند/ندهند.<br>', verbose_name='فعال کردن ثبتنام در این دسته'),
        ),
        migrations.AlterField(
            model_name='themostcategory',
            name='description',
            field=models.TextField(blank=True, help_text='این توضیح را دانشجویان هنگام تصیم برای عضویت در این دسته می\u200cتوانند ببینید.<br>در صفحه\u200cای که اجازه گرفته می\u200cشود، زیر این توضیح، لیست ترین\u200cهای این دسته آورده می\u200cشود.', verbose_name='توضیح دسته'),
        ),
        migrations.AlterField(
            model_name='themostcategory',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان دسته'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='date',
            field=models.DateField(help_text='این تاریخ به صورت میلادی وارد می\u200cشود و اتفاقات بر حسب این مقدار در گاه\u200cشمار مرتب می\u200cشوند.', verbose_name='تاریخ اتفاق'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='image',
            field=models.ImageField(blank=True, upload_to=main.models.timeline_image_path, verbose_name='عکس این اتفاق'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='image_folder',
            field=models.URLField(blank=True, help_text='هر عکس در گاه\u200cشمار می\u200cتواند به لینکی متصل باشه که شامل عکس\u200cهای بیشتر از این اتفاق باشد.<br>مثلاً می\u200cتوانید از گوگل درایو استفاده کنید.<br>لینکی که دوست دارید را اینجا قرار دهید. می\u200cتواند خالی باشد.', verbose_name='لینک به پوشه عکس'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='show_date',
            field=models.CharField(help_text='آنچه در این کادر نوشته می\u200cشود به صورت یک متن در کنار عکس این اتفاق آورده می\u200cشود. ', max_length=100, verbose_name='تاریخ این اتفاق'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='title',
            field=models.TextField(verbose_name='عنوان اتفاق'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=180, null=True, verbose_name='بایو'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('Man', 'Man'), ('Woman', 'Woman')], default=main.models.Gender('Man'), max_length=10, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='most_candidate',
            field=models.BooleanField(default=True, verbose_name='کاندید برای ترین\u200cها'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, storage=main.storage.OverwriteStorage(), upload_to=main.models.image_path, verbose_name='عکس پروفایل'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='will_participate',
            field=models.BooleanField(default=True, verbose_name='در جشن شرکت می\u200cکند؟'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='main.UserProfile', verbose_name='کاندید'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='is_submitted',
            field=models.BooleanField(default=False, verbose_name='ارسال شده'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='old_candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_candidate', to='main.UserProfile', verbose_name='کاندید قبلی'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='the_most',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TheMost', verbose_name='عنوان ترین'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='زمان ارسال'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voter', to='main.UserProfile', verbose_name='رای\u200cدهنده'),
        ),
    ]
